konstellation-io/kai-kli

- go.mod
- go.sum
Update the graphql library version to the latest version to fix file upload issues.
> fix(graphql): updte the graphql library to the latest version

- cmd/server/add.go
- cmd/server/default.go
- cmd/server/remove.go
- cmd/server/server.go
- internal/configuration/kai_server_configuration.go
- internal/server/add.go
- internal/server/add_test.go
- internal/server/remove.go
- internal/server/remove_test.go
- internal/server/set_default.go
- scripts/generate_release.sh
Add remove server command
The remove server command should remove an existing server from the server list.
If the server to be removed is defined as the default, the first server from the list will be defined as the new default.
> Add remove server command 

- README.md
- cmd/root/root.go
- cmd/server/add.go
- cmd/server/login.go
- cmd/server/logout.go
- cmd/server/server.go
- internal/commands/server/login_test.go
- internal/commands/server/logout.go
- internal/commands/server/logout_test.go
- internal/commands/server/set_default_test.go
- internal/render/renderer.go
- internal/services/auth/authentication_service.go
- internal/services/auth/authentication_service_test.go
Add logout command.
This command will remove all credentials and session tokens from the KLI configuration, and will close any opened session on Keycloak.
> Logout command

- .github/workflows/pre-release.yml
- .github/workflows/release.yml
Update `intelygenz/action-product-version-tags`action to v0.2.1
> ci: update intelygenz/action-product-version-tags to v0.2.1

- cmd/server/login.go
- internal/commands/server/login.go
- internal/commands/server/login_test.go
- internal/commands/server/logout_test.go
- internal/commands/server/set_default_test.go
- internal/services/auth/authentication_service.go
- internal/services/auth/authentication_service_test.go
- internal/services/configuration/configuration_service_test.go
- internal/services/configuration/kai_configuration.go
- internal/services/configuration/kai_configuration_test.go
As the new authentication redirects the user through the browser, we don't need to store the authentication credentials anymore.
> Remove credentials from authentication

- .github/workflows/goreleaser.yml
- .goreleaser.yml
- README.md
This PR add config for goreleaser that allows to publish KLI into a Homebrew tap.
We want to publish KLI on as much registries as possible.
> ci: add brews config to goreleaser

- .github/workflows/quality.yml
This PR update the following Github Actions to their newest versions.
* checkout: v3
* setup-go: v4
> ci: update github actions

- .goreleaser.yml
Fixes the command `kli version` result
> fix: gorelease build template

- .github/workflows/goreleaser.yml
- .goreleaser.yml
- README.md
Publish Windows binaries via a package manager. 
We need KLI to be installed on windows via a package manager. Scoop is the chosen solution.
> feat: add scoop to goreleaser

- cmd/server/login.go
> fix: protocol schema checks

- .github/workflows/test-release.yml
- CHANGELOG.tpl
Fixes Nyx CI auth token  and CHANGELOG.tpl
> ci: fix Nyx auth token and CHANGELOG.tpl

- authserver/authserver.go
Print login request url if the redirect fails on server login command.
> Print login request url if the redirect fails

- go.mod
- go.sum
- internal/commands/processregistry/register.go
Ignore files via .krtignore on the register process command.
> feat: add .krtignore file support

- authserver/authserver.go
> Fix server login message

- demo/.kai/demo2.yaml
> Delete unused demo directory

- internal/commands/version/start.go
- internal/commands/version/start_test.go
> feature(kai-kli): Add warning when starting critical status versions

- go.mod
- go.sum
- internal/commands/configuration/add_test.go
- internal/commands/configuration/list_test.go
- internal/commands/configuration/remove_test.go
- internal/commands/process/add_test.go
- internal/commands/process/handler.go
- internal/commands/process/helpers_test.go
- internal/commands/version/testdata/test-product.yaml
- internal/services/product_configuration/kai_product_configuration_test.go
- internal/services/product_configuration/product_configuration_service_test.go
By default we want know HTTP protocol, UDP and TCP are deprecated now is HTTP or GRPC
> fix: update protocol from tcp to http, update tests

- internal/logging/logger.go
We are skipping logs for json renderer as we already covered the important ones with custom renderers, we will add more custom renderer for missing logs is required in the future
> fix: skip normal logs in json renderer

- api/kai/interface.go
- api/product/client.go
- api/version/publish.go
- cmd/product/version/get.go
- cmd/product/version/list.go
- cmd/product/version/logs.go
- cmd/product/version/publish.go
- cmd/product/version/push.go
- cmd/product/version/start.go
- cmd/product/version/stop.go
- cmd/product/version/unpublish.go
- internal/commands/version/handler.go
- internal/commands/version/publish.go
- internal/commands/version/publish_test.go
- internal/commands/version/start.go
- internal/commands/version/suite_test.go
- internal/entity/version.go
- mocks/version_client.go
> feat: add force publish option when another version is published

- cmd/main.go
When the cmd command has an error we are logging it but not returning an error code, this is required for worklfows
> fix: missing code error

- cmd/main.go
> fix: missing code error (#82)

- .gitignore
- cmd/server/server.go
- internal/commands/version/push.go
- internal/commands/version/push_test.go
- internal/render/interface.go
- internal/render/json-renderer.go
- internal/render/text-renderer.go
- mocks/renderer.go
- added renderer for text and json in push version log
> fix: json render for push version

- internal/render/json-renderer.go
Get version json now logs correctly
> fix: get version json

- .github/workflows/goreleaser.yml
- .goreleaser.yml
- Dockerfile
This PR adds a Docker image for KAI KLI
> ci: add docker image

- .goreleaser.yml
> chore: aaa 111 merge main into develop

- internal/commands/product/bind.go
- internal/commands/product/bind_test.go
- internal/render/interface.go
- internal/render/json-renderer.go
- internal/render/text-renderer.go
- mocks/renderer.go
bind product now uses the render interface
> fix: bind product render

- cmd/product/version/list.go
- internal/commands/version/list.go
- internal/render/json-renderer.go
- Added a status filter to list product version command
> feat: add status filter to list product versions

- authserver/authserver.go
- cmd/configuration/list.go
- cmd/process/add.go
- cmd/process/list.go
- cmd/process/process.go
- cmd/process/update.go
- cmd/product/list.go
- cmd/root/root.go
- cmd/root/version.go
- cmd/server/list.go
- cmd/server/login.go
- cmd/server/logout.go
- cmd/storage/open.go
- cmd/workflow/list.go
- go.mod
- go.sum
- internal/commands/process/add.go
- internal/commands/process/handler.go
- internal/commands/process/update.go
- internal/commands/processregistry/register.go
- internal/entity/version.go
- internal/render/json-renderer.go
- internal/render/text-renderer.go
- internal/services/product_configuration/kai_product_configuration_processes.go
- pkg/krtutil/krtutil.go
> feat: add support for processes' node selectors

- api/processregistry/delete.go
- api/processregistry/process_registry.go
- cmd/processregistry/delete.go
- cmd/processregistry/process_registry.go
- cmd/processregistry/register.go
- internal/commands/processregistry/delete.go
- internal/commands/processregistry/delete_test.go
- internal/render/interface.go
- internal/render/json-renderer.go
- internal/render/text-renderer.go
- mocks/registry_client.go
- mocks/renderer.go
- Add command for delete process
- Added api, service, command and renderer layers
> feat: process registry delete kli support

- internal/services/auth/authentication_service.go
> fix: manage refresh token errors

- api/kai/interface.go
- api/product/client.go
- cmd/product/list.go
- internal/commands/product/list.go
- internal/commands/product/list_test.go
- internal/commands/version/list.go
- mocks/product_client.go
- Removed unused flags for product ls
- Added filter to product ls
> feat: add produc tname filters to product ls

- api/kai/interface.go
- api/version/list.go
- cmd/product/version/list.go
- internal/commands/version/list.go
- internal/commands/version/list_test.go
- internal/entity/version.go
- mocks/version_client.go
- Deprecated old internal filter logic
- Now we use the filter attribute in endpoint
- Updated tests
> feat: use new status filter for product version list endpoint
